DELETE http://localhost:3003/api/blogs/6863802ca7fdd7cc1af0a7b0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImxpY2hpZ3V5IiwiaWQiOiI2ODYzNjY0NWM1ZTBmMjVmN2RlMmU3NjEiLCJpYXQiOjE3NTEzNTExMjksImV4cCI6MTc1MTM1NDcyOX0.FaLajiJRxFnvcQxGLEsDvhSvrdgrjB46RWJzBjw15As